import { genderField } from './gender';
import { jobDepartmentField } from './jobDepartment';

export const addFormFields = {
  regNumber: {
    type: 'text',
    name: 'regNumber',
    label: 'Registration Number',
    bn_label: 'নিবন্ধন সংখ্যা',
    placeholder: 'B-0123',
    value: 'B-',
  },
  name: {
    type: 'text',
    name: 'name',
    label: 'Pharmacist Name (English)',
    bn_label: 'ফার্মাসিস্টের নাম (English)',
    placeholder: 'ABDULLAH',
    value: '',
  },
  bn_name: {
    type: 'text',
    name: 'bn_name',
    label: 'Pharmacist Name (বাংলা)',
    bn_label: 'ফার্মাসিস্টের নাম (বাংলা)',
    placeholder: 'আবদুল্লাহ',
    value: '',
  },
  fathersName: {
    type: 'text',
    name: 'fathersName',
    label: "Father's Name (English)",
    bn_label: 'পিতার নাম (English)',
    placeholder: 'ABDUR RAHMAN',
    value: '',
  },
  bn_fathersName: {
    type: 'text',
    name: 'bn_fathersName',
    label: "Father's Name (বাংলা)",
    bn_label: 'পিতার নাম (বাংলা)',
    placeholder: 'আব্দুর রহমান',
    value: '',
  },
  mothersName: {
    type: 'text',
    name: 'mothersName',
    label: "Mother's Name  (English)",
    bn_label: 'মায়ের নাম (English)',
    placeholder: 'AYESHA',
    value: '',
  },
  bn_mothersName: {
    type: 'text',
    name: 'bn_mothersName',
    label: "Mother's Name (বাংলা)",
    bn_label: 'মায়ের নাম (বাংলা)',
    placeholder: 'আয়েশা',
    value: '',
  },
  email: {
    type: 'email',
    name: 'email',
    label: 'Email',
    bn_label: 'ইমেইল',
    placeholder: 'abdullah@email.com',
    value: '',
  },
  mobile: {
    type: 'text',
    name: 'mobile',
    label: 'Mobile Number',
    bn_label: 'মোবাইল নাম্বার',
    placeholder: '01712123456',
    value: '',
  },
  dateOfBirth: {
    type: 'date',
    name: 'dateOfBirth',
    label: 'Date of Birth',
    bn_label: 'জন্ম তারিখ',
    value: null,
  },
  gender: { ...genderField },
  nationalId: {
    type: 'text',
    name: 'nationalId',
    label: 'National ID Number',
    bn_label: 'জাতীয় পরিচয়পত্র সংখ্যা',
    placeholder: '1372362372',
    value: '',
  },
  passingYear: {
    type: 'text',
    name: 'passingYear',
    label: 'Diploma Passing Year',
    bn_label: 'ডিপ্লোমা পাশের বছর',
    placeholder: '2012',
    value: '',
  },
  institute: {
    type: 'text',
    name: 'institute',
    label: 'Diploma Institute Name (English)',
    bn_label: 'ডিপ্লোমা ইনস্টিটিউটের নাম (English)',
    placeholder: 'Institute of Health Technology, Rajshahi',
    value: '',
  },
  bn_institute: {
    type: 'text',
    name: 'bn_institute',
    label: 'Diploma Institute Name (বাংলা)',
    bn_label: 'ডিপ্লোমা ইনস্টিটিউটের নাম (বাংলা)',
    placeholder: 'ইনস্টিটিউট অব হেলথ টেকনোলজি, রাজশাহী',
    value: '',
  },
  memberId: {
    type: 'text',
    name: 'memberId',
    label: 'BDPA Member ID',
    bn_label: 'বিডিপিএ সদস্য পরিচিতি',
    placeholder: 'BDP00321',
    value: '',
  },
  imageUrl: {
    type: 'text',
    name: 'imageUrl',
    label: 'Image URL (link)',
    bn_label: 'ইমেজ ইউআরএল (লিঙ্ক)',
    placeholder: 'https://bdpa.org/image/member7.jpg',
    value: '',
  },
  dateOfJoin: {
    type: 'date',
    name: 'dateOfJoin',
    label: 'Date of Join',
    bn_label: 'যোগদানের তারিখ',
    value: null,
  },
  jobDepartment: { ...jobDepartmentField },
};
